language: java
os: linux
dist: xenial
sudo: false
jdk:
- openjdk-ea
script: mvn clean verify
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: XIa+Hey1u0a/mOM5FSAmG2uaCxva314/G/DaEZ8GeKHBEOlumPusvcHRlxWruadyFGJvcVmCOHNcYeyQW5Syxb6zn+ElJLu9JjoB2UHLzStSX5Mj58l3gfns+LvEBMeL4AFmszFeKeM4ZAheVVgGO9lvQtkB0G5ViBgYySuSSPBssecxE+nb7BjuI3Th4rQ/lII3r93+Hl8lXWgGoiBva1PYmh5wjkhONpa01tVo47PeGqPCZpCd1yQhnLjU8Bb1tqpbr6YWSZe2K5KXv6lkDOKu6e2tzplw+0PPhegD5eESYsz7Y3P9e+N9VWlEyJaezeFzPkeTj6y9HZcOT5gwudNNmIJXJoD3QlZf8Yz7kwZnC7dH5iRKrqmNs13sMEVNsQi5JrZ5zQta1DwsVxN6o/PquMI9w7vA8SWe/ZdQeUjHPpkTCReJnkahae+rH6PrOZBvfbdpk5gz5lTdbFhhv8ztYdRyQns5ITpRqa3CtjiMipVg9F9jFl0gsmIVPixhmofKms9FXA7IHoHWrMD+YZHSvl5Qc1/uY5UG1L43vfTQEaot0Hjg6r27KPwd0YHoX1fF5AZyVdm8tHsT1OyvpLpGwZJZtddKoS1f6xUn08OXC+FCOzJg34Xy2IFK1CSKMj9tTLz66hk5GQFlGPqqOGyxEsHS9sXTo22o0+l+8j8=
  - secure: ZLnW/pWPkY9tjo3HAaFJamsZVDbwLiyGdXkX/bxzTR0wSWvvcjW/FoN9N0eKkrsIYF0qRKu8QS67Z3Sa5Em/H7smhlwXZmHkBQfVPNyt7Fsv1BF76R+imE/nJOSoZkRVqrHrjCK7NOnR05Nae6U+VaKntRoiN1gsnbN/vKIzd1hI9Z+lIbiYLshJAVMu6+eegl80EcK2bSX4jM2JQx+vZ4GKguZSQ1RMQD85lG8YrtmkNGfh6iIJymDN/MqI/F5G2w3N77OGTDdrlXJrerbqMAdMTcEzpCPJeR6E65KaRA2VNHnqxLHmrKguvNpvwoiF0opcZlNwv14d8EI83flT9xYTneigUueuVKZyxEXPTw863A4F3MBHAxYN4iUoTcQyfpY9W9bCyIU/QGYhGymsvVcIJ6P+emFmI5n07q6Hy9v9bO8DqmmKLysazJEfTys6nMRkj8/VoafgzV1ohqX50ioaLtkqcdxqYy02Q89N3OxCkZG9Hm7/pblPXOujPDtX5XPp9Kmtdll5hOStK+V+Zl/6GBGcOyasjgRa9p9Wzf+n8LAfp5W/HZpObdEA4daYGWnR0O338hN4jEVEa76mIoTYCZdtIxPqXi8vdeJ/SMCcQF25AjoP8m9QTFGhpzhS8FEYOjII5CMTGS/jbN0dRSd584d49JEkQDUkfnEbBIs=